version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ecommerce_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/ecommerce_db
      - PORT=3001
    depends_on:
      - mongodb
    networks:
      - microservices-network

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/ecommerce_db
      - PORT=3002
    depends_on:
      - mongodb
    networks:
      - microservices-network

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/ecommerce_db
      - PORT=3003
    depends_on:
      - mongodb
    networks:
      - microservices-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "3004:3004"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/ecommerce_db
      - PORT=3004
    depends_on:
      - mongodb
    networks:
      - microservices-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3005:3005"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/ecommerce_db
      - PORT=3005
    depends_on:
      - mongodb
    networks:
      - microservices-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - USER_SERVICE_URL=http://user-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - ORDER_SERVICE_URL=http://order-service:3003
      - PAYMENT_SERVICE_URL=http://payment-service:3004
      - NOTIFICATION_SERVICE_URL=http://notification-service:3005
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
      - notification-service
    networks:
      - microservices-network

volumes:
  mongodb_data:

networks:
  microservices-network:
    driver: bridge