apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: kastrov/product-service:IMAGE_TAG
        ports:
        - containerPort: 3002
        env:
        - name: MONGODB_URI
          value: "mongodb://admin:password@mongodb-service:27017/ecommerce_db"
        - name: PORT
          value: "3002"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5